### ISSUE TITLE
License Missing

### ISSUE THREAD

**Issue by therealkbhat** [chinmaydd/SchemER#6]
If we are indeed open-sourcing this and allowing for anyone to use it, we need an appropriate license.

The [MIT license](http://opensource.org/licenses/MIT) fits best, I think. Thoughts?

Other candidates can be found [here](http://choosealicense.com/).

**Comment by chinmaydd** [comment]
Yeah, i think the MIT license is pretty good. But since we have GoJS code in our repository, we can't just yet add the license. We could add the javascript file as an external include and then add the license.

**Comment by therealkbhat** [comment]
Sounds good to me. :+1:

**Comment by chinmaydd** [comment]
Removed GoJS from static folder \o/. Safe to close.
